"""the column name correction

Revision ID: 1e099cda2386
Revises: 2bb7005ffbb6
Create Date: 2026-07-23 17:39:17.435635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e099cda2386'
down_revision: Union[str, Sequence[str], None] = '2bb7005ffbb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.drop_column('contracts', 'orignal_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('orignal_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('contracts', 'original_filename')
    # ### end Alembic commands ###
