"""correct a contract table column name

Revision ID: 2bb7005ffbb6
Revises: 593bba016c4c
Create Date: 2026-07-20 18:26:23.024184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb7005ffbb6'
down_revision: Union[str, Sequence[str], None] = '593bba016c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.drop_column('contracts', 'contract_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('contracts', 'content_type')
    # ### end Alembic commands ###
