"""i make contract table sutable for a future contract analysis table.

Revision ID: 513f936991c8
Revises: c76ac58aced8
Create Date: 2026-07-26 10:43:54.531380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513f936991c8'
down_revision: Union[str, Sequence[str], None] = 'c76ac58aced8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('contracts', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'processed_at')
    op.drop_column('contracts', 'last_error')
    # ### end Alembic commands ###
